Fix Brotli encoding error (use HEAD to check on build)
GET request fails due to Brotli encoding error:
    AxiosError: unexpected end of file (code = Z_BUF_ERROR)

We could opt-out of Brotli compression with an Accept-Encoding header, but it's simpler to just do a HEAD request since we just care about the deploy's progress, not about the HTML contents.